import numpy as np


def get_embedding(face):
    """
    Get the face embedding generated by InsightFace.
    """

    embedding = face.embedding

    if embedding is None:
        return None

    embedding = np.asarray(embedding, dtype=np.float32)

    # Normalize the embedding
    norm = np.linalg.norm(embedding)

    if norm == 0:
        return None

    return embedding / norm